apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: hpc-cache-terraform
  title: HPC Cache Terraform Variables
  description: Template to configure variables for HPC Cache in Terraform
spec:
  owner: your-team-name
  type: terraform
  parameters:
    - title: HPC Cache Configuration
      properties:
        name:
          type: string
          title: HPC Cache Name
          description: "The name of the HPC Cache."
          required: true
        resource_group_name:
          type: string
          title: Resource Group Name
          description: "The name of the Resource Group in which to create the HPC Cache."
          required: true
        location:
          type: string
          title: Azure Location
          description: "Specifies the Azure Region for the HPC Cache."
          required: true
        cache_size_in_gb:
          type: number
          title: Cache Size (GB)
          description: "The size of the HPC Cache, in GB."
          enum:
            - 3072
            - 6144
            - 12288
            - 21623
            - 24576
            - 43246
            - 49152
            - 86491
          required: true
        subnet_id:
          type: string
          title: Subnet ID
          description: "The ID of the Subnet for the HPC Cache."
          required: true
        sku_name:
          type: string
          title: SKU Name
          description: "The SKU of the HPC Cache."
          enum:
            - Standard_2G
            - Standard_4G
            - Standard_8G
            - Standard_L4_5G
            - Standard_L9G
            - Standard_L16G
          required: true
        mtu:
          type: number
          title: MTU
          description: "The IPv4 MTU for the subnet."
          default: 1500
          minimum: 576
          maximum: 1500
        default_access_policy_config:
          type: object
          title: Default Access Policy
          properties:
            access_rule_config:
              type: array
              items:
                type: object
                properties:
                  scope: { type: string }
                  access: { type: string }
                  filter: { type: string, nullable: true }
                  suid_enabled: { type: boolean }
                  submount_access_enabled: { type: boolean }
                  root_squash_enabled: { type: boolean }
                  anonymous_uid: { type: string, nullable: true }
                  anonymous_gid: { type: string, nullable: true }
              default:
                - scope: "default"
                  access: "no"
                  filter: null
                  suid_enabled: false
                  submount_access_enabled: false
                  root_squash_enabled: false
                  anonymous_uid: null
                  anonymous_gid: null
        ntp_server:
          type: string
          title: NTP Server
          description: "The NTP server for the HPC Cache."
          default: "time.windows.com"
        dns_config:
          type: object
          title: DNS Configuration
          properties:
            servers: 
              type: array
              items: { type: string, nullable: true }
            search_domain: { type: string, nullable: true }
        directory_active_directory_config:
          type: object
          title: Directory Active Directory Config
          properties:
            dns_primary_ip: { type: string, nullable: true }
            domain_name: { type: string, nullable: true }
            cache_netbios_name: { type: string, nullable: true }
            domain_netbios_name: { type: string, nullable: true }
            username: { type: string, nullable: true }
            password: { type: string, nullable: true }
            dns_secondary_ip: { type: string, nullable: true }
        identity_config:
          type: object
          title: Identity Configuration
          properties:
            type: { type: string, nullable: true }
            identity_ids: { type: string, nullable: true }
        key_vault_key_id:
          type: string
          title: Key Vault Key ID
          description: "The ID of the Key Vault Key."
          default: null
        automatically_rotate_key_to_latest_enabled:
          type: string
          title: Automatically Rotate Key
          description: "Specifies if the HPC Cache rotates the key automatically."
          default: null
        tags:
          type: object
          title: Tags
          additionalProperties: { type: string, nullable: true }

  steps:
    - id: create
      name: Create Terraform Variables
      action: terraform:create
      input: 
        name: '{{ parameters.name }}'
        resource_group_name: '{{ parameters.resource_group_name }}'
        location: '{{ parameters.location }}'
        cache_size_in_gb: '{{ parameters.cache_size_in_gb }}'
        subnet_id: '{{ parameters.subnet_id }}'
        sku_name: '{{ parameters.sku_name }}'
        mtu: '{{ parameters.mtu }}'
        default_access_policy_config: '{{ parameters.default_access_policy_config }}'
        ntp_server: '{{ parameters.ntp_server }}'
        dns_config: '{{ parameters.dns_config }}'
        directory_active_directory_config: '{{ parameters.directory_active_directory_config }}'
        identity_config: '{{ parameters.identity_config }}'
        key_vault_key_id: '{{ parameters.key_vault_key_id }}'
        automatically_rotate_key_to_latest_enabled: '{{ parameters.automatically_rotate_key_to_latest_enabled }}'
        tags: '{{ parameters.tags }}'
